create extension if not exists "pgcrypto";

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  x_user_id text unique,
  x_username text,
  display_name text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  image_url text,
  stock integer not null default 0,
  price text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists services (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  image_url text,
  price text not null,
  estimated_time text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists testimonial_access (
  id bigint generated by default as identity primary key,
  x_user_id text unique not null,
  x_username text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists faq (
  id bigint generated by default as identity primary key,
  question text not null,
  answer text not null,
  published boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  item_type text not null check (item_type in ('stuff', 'joki')),
  product_id bigint references products(id) on delete set null,
  service_id bigint references services(id) on delete set null,
  item_name text not null,
  quantity integer not null default 1,
  total_price text not null,
  payment_method text not null default 'qris',
  payment_status text not null default 'unpaid',
  order_status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists site_settings (
  id integer primary key default 1,
  qr_image_url text,
  x_username text default 'gleebiwn',
  shop_status text default 'open',
  updated_at timestamptz not null default now()
);

insert into site_settings (id, x_username)
values (1, 'gleebiwn')
on conflict (id) do nothing;